spring.application.name=LiquiBasePostgressSQL
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres